version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - mykiwi
  ignore:
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
