version: '3.7'

services:
  postgresql:
    image: postgres:11.2-alpine

  redis:
    image: redis:5.0-alpine

  # if `max virtual memory areas vm.max_map_count [65530] is too low...`: run `sudo sysctl -w vm.max_map_count=262144`
  elasticsearch:
    image: elasticsearch:7.0.0
    environment:
      cluster.name: es
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m

  http:
    image: 3615/webhook:dev
    volumes:
      - ./:/srv

  workers:
    image: 3615/webhook:dev
    command: supervisord --nodaemon --configuration /etc/supervisor/workers.conf
    volumes:
      - ./:/srv


  tools:
    image: 3615/webhook:tools
    command: sleep 999d
    volumes:
      - ./:/srv
