version: 2.1
jobs:
  build:
    docker:
      - image: mykiwi/docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
