#!/bin/sh
set -e

if [ "${HAPROXY_DEFAULT_SSL_CERT}" ]; then
    mkdir -p /usr/local/etc/haproxy/ssl
    echo "${HAPROXY_DEFAULT_SSL_CERT}" > /usr/local/etc/haproxy/ssl/default.pem
fi
unset HAPROXY_DEFAULT_SSL_CERT

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- haproxy "$@"
fi

if [ "$1" = 'haproxy' ]; then
	shift # "haproxy"
	# if the user wants "haproxy", let's add a couple useful flags
	#   -W  -- "master-worker mode" (similar to the old "haproxy-systemd-wrapper"; allows for reload via "SIGUSR2")
	#   -db -- disables background mode
	set -- haproxy -W -db "$@"
fi

exec "$@"
